---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app
      namespace: arr

    controllers:
      sabnzbd:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: &group 1000
            fsGroup: *group
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.1
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                {{ .Release.Name }},
                {{ .Release.Name }}.arr,
                {{ .Release.Name }}.arr.svc,
                {{ .Release.Name }}.arr.svc.cluster.local,
                sab.${LOCAL_DOMAIN}

            probes:
              liveness:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

            resources:
              requests:
                cpu: 20m
                memory: 200Mi
              limits:
                memory: 4000Mi

          metrics:
            dependsOn: app
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.2.0
            env:
              PORT: &metricsPort 9707
              URL: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8080"
              APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: recyclarr-secrets
                    key: SABNZBD_API_KEY
            args: ["sabnzbd"]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi

    service:
      app:
        primary: true
        controller: sabnzbd
        ports:
          http:
            port: *port
      metrics:
        controller: sabnzbd
        ports:
          metrics:
            port: *metricsPort

    serviceMonitor:
      main:
        enabled: true
        serviceName: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-metrics'
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    ingress:
      internal:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: /outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: "sab.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
              - path: /metrics
                pathType: Prefix
                service:
                  identifier: metrics
                  port: metrics
        tls:
          - hosts:
              - "sab.${LOCAL_DOMAIN}"
            secretName: local-mafyuh-dev-production-tls

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
        globalMounts:
          - path: /config

      data:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: /mnt/thePool/thePoolShare
        globalMounts:
          - path: /data
      
      incomplete:
        enabled: true
        type: emptyDir
        sizeLimit: 100Gi
        globalMounts:
          - path: /incomplete