---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyseerr
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app
      namespace: arr

    controllers:
      jellyseerr:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1
        
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: &group 1000
            fsGroup: *group
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: fallenbagel/jellyseerr
              tag: 2.5.2
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              LOG_LEVEL: info

            probes:
              liveness:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      app:
        primary: true
        controller: jellyseerr
        ports:
          http:
            port: 5055

    ingress:
      internal:
        enabled: true
        className: nginx
        hosts:
          - host: "request.${PUBLIC_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "request.${PUBLIC_DOMAIN}"
            secretName: mafyuh-dev-production-tls
    
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: longhorn
        globalMounts:
          - path: /app/config