apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cilium-resources
  namespace: kube-system
resources:
  - source.yaml
  - helm-release.yaml
  - cilium-loadbalancer-ippool.yaml
  - cilium-l2-announcement-policy.yaml