---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: merox-dev
  namespace: cert-manager
spec:
  secretName: merox-dev-production-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.merox.dev"
  dnsNames:
  - "*.merox.dev"