apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-config
  namespace: default
type: Opaque
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogJ25vZGVfZXhwb3J0ZXInCiAgc2NyYXBlX2ludGVydmFsOiAxNXMKICBzdGF0aWNfY29uZmlnczoKICAgIC0gdGFyZ2V0czogWycxMC42OS42OS4yMDA6OTEwMCddCiAgICAtIHRhcmdldHM6IFsnMTAuNjkuNjkuMTUwOjkxMDAnXQogICAgLSB0YXJnZXRzOiBbJzEwLjAuMC4xNTo5MTAwJ10KICAgIC0gdGFyZ2V0czogWycxMC4wLjAuNDA6OTEwMCddCiAgICAtIHRhcmdldHM6IFsnMTAuNjkuNjkuMTg5OjkxMDAnXQogICAgLSB0YXJnZXRzOiBbJzEwLjY5LjY5LjI6OTEwMCddCgotIGpvYl9uYW1lOiAnY2Fkdmlzb3InCiAgc2NyYXBlX2ludGVydmFsOiAxNXMKICBzdGF0aWNfY29uZmlnczoKICAgIC0gdGFyZ2V0czogWycxMC42OS42OS4yMDA6OTEwMSddCiAgICAtIHRhcmdldHM6IFsnMTAuNjkuNjkuMTUwOjkxMDEnXQogICAgLSB0YXJnZXRzOiBbJzEwLjAuMC4xNTo5MTAxJ10KICAgIC0gdGFyZ2V0czogWycxMC4wLjAuNDA6OTEwMSddCiAgICAtIHRhcmdldHM6IFsnMTAuNjkuNjkuMTg5OjkxMDEnXQogICAgLSB0YXJnZXRzOiBbJzEwLjY5LjY5LjI6OTEwMSddCg==