apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 73.2.0
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: prometheus
    crds:
      enabled: true
    alertmanager:
      enabled: false
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    grafana:
      enabled: true
      replicas: 1
      forceDeployDashboards: false
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: America/New_York
      defaultDashboardsEditable: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: /outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - "grafana.${PUBLIC_DOMAIN}"
        path: /
        tls:
          - secretName: mafyuh-dev-production-tls
            hosts:
              - "grafana.${PUBLIC_DOMAIN}"
      adminPassword: "${GRAF_ADMIN_PASS}"
      persistence:
        enabled: true
        type: sts
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        finalizers:
          - kubernetes.io/pvc-protection

    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - "prometheus.${LOCAL_DOMAIN}"
        pathType: Prefix
        tls:
          - secretName: local-mafyuh-dev-production-tls
            hosts:
              - "prometheus.${LOCAL_DOMAIN}"
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        additionalScrapeConfigsSecret:
          enabled: true
          name: prometheus-additional-config
          key: additional-scrape-configs.yaml
        replicas: 1
        retention: 14d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 30Gi
