apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  # Comentăm temporar până cert-manager e ready
  # - certificates/local.yaml
  # - certificates/public.yaml
  # - issuers/letsencrypt.yaml
  # - issuers/secret-cf-token.yaml
