---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbitty
  namespace: arr
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app
      namespace: arr

    controllers:
      qbitty:
        enabled: true
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"

        replicas: 1

        containers:
          app:
            image:
              repository: ghcr.io/hotio/qbittorrent
              tag: release-5.0.5
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
              WEBUI_PORT: &port 8080
              VPN_ENABLED: "true"
              VPN_CONF: "wg0"
              VPN_PROVIDER: "proton"
              VPN_KEEP_LOCAL_DNS: "false"
              VPN_AUTO_PORT_FORWARD: "true"
              VPN_LAN_NETWORK:
                valueFrom:
                  secretKeyRef:
                    name: lan-network
                    key: lan-network
              VPN_LAN_LEAK_ENABLED: "false"
              VPN_FIREWALL_TYPE: "auto"
              PRIVOXY_ENABLED: "false"
              VPN_HEALTHCHECK_ENABLED: "false"
              UNBOUND_ENABLED: "false"
            
            probes:
              liveness:
                enabled: false

            securityContext:
              capabilities:
                add:
                  - NET_ADMIN

            resources:
              requests:
                cpu: 20m
                memory: 200Mi
              limits:
                memory: 4000Mi

    service:
      app:
        primary: true
        controller: qbitty
        ports:
          http:
            port: *port

    ingress:
      internal:
        enabled: true
        className: nginx
        hosts:
          - host: "qbitty.${LOCAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - "qbitty.${LOCAL_DOMAIN}"
            secretName: local-mafyuh-dev-production-tls

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 500Mi
        storageClass: longhorn
        globalMounts:
          - path: /config

      data:
        enabled: true
        type: nfs
        server: "${NAS_IP}"
        path: /mnt/thePool/thePoolShare
        globalMounts:
          - path: /data

      incomplete:
        enabled: true
        type: emptyDir
        sizeLimit: 100Gi
        globalMounts:
          - path: /incomplete

      wireguard-config:
        enabled: true
        type: secret
        name: qbitty-wireguard
        defaultMode: 0400
        globalMounts:
          - path: /config/wireguard/wg0.conf
            subPath: wg0.conf
